// load mongoose module
var mongoose = require('mongoose');
// load helper module
var helper = require('./helper');

// access mongoose schema instance
var LocationModel = mongoose.model('Location');

// GET location by ID
module.exports.read = function (req, res) {
  LocationModel
    // find location document by id
    .findById(req.params.locationid)
    // execute query with callback function
    .exec(function(err, location) {
      // check if a location document got returned from the query
      if (!location) {
        // if no location document got returned send 404 not found and return to caller
        helper.sendJsonResponse(res, 404, {
          "message": "no location with id " + req.params.locationid
        });
        return;
      // check for errors
      } else if (err) {
        // if there are errors send 400 bad request and return to caller
        helper.sendJsonResponse(res, 400, err);
        return;
      }
      // send location document and 200 Ok
      helper.sendJsonResponse(res, 200, location);
    });
};

// GET location list sorted by distance
module.exports.listByDistance = function(req, res) {

  // Get parameters from url
  var longitude = parseFloat(req.query.longitude);
  var latitude = parseFloat(req.query.latitude);
  var maxElements = parseInt(req.query.maxElements);
  var distance = parseInt(req.query.distance);
  // Check if parameters are null
  if (!longitude && longitude !==0 || !latitude && latitude !==0 || !maxElements || !distance) {
    // if there are parameters with null, send 400 bad request and return to caller
    helper.sendJsonResponse(res, 404, {
      "message": "required query parameters are longitude, latitude, maxElements, distance in meter"
    });
    return;
  }

  // create a point object for querying by distance
  var point = {
    type: "Point",
    coordinates: [longitude, latitude]
  };
  // create options object for parameterizing the query
  var options = {
    spherical: true,
    maxDistance: distance,
    num: maxElements
  };
  // execute geoNear Query
  LocationModel.geoNear(point, options, function(err, result, stats) {
    var locations = [];
    // Check for errors
    if (err) {
      helper.sendJsonResponse(res, 404, err);
    }
    // Loop through results and parse each result
    result.forEach(function(element) {
      locations.push({
        _id: element.obj._id,
        theme: element.obj.theme,
        address: element.obj.address,
        datum: element.obj.datum,
        coords: element.obj.coords,
        comments: element.obj.comments,
        participants: element.obj.participants,
        required: element.obj.required,
        provided: element.obj.provided,
        distance: element.dis,
        createdOn: element.obj.createdOn
      });
    });
    helper.sendJsonResponse(res, 200, locations);
  });
};

// POST location
module.exports.create = function(req, res) {
  LocationModel.create({
    // id is autogenerated
    // createdOn is autogenerated
    theme: req.body.theme,
    address: req.body.address,
    datum: req.body.datum,
    coords: [parseFloat(req.body.longitude),
      parseFloat(req.body.latitude)],
    participants: req.body.participants,
    required: req.body.required,
    provided: req.body.provided
  }, function(err, location) {
    if (err) {
      helper.sendJsonResponse(res, 404, err);
      return;
    }
    helper.sendJsonResponse(res, 201, location);
  })
}

// PUT location by ID
module.exports.update = function (req, res) {
  LocationModel
    .findById(req.params.locationid)
    // Exclude comments as they are updated seperately in commentsController
    .select('-comments')
    .exec(function(err, doc) {
      if (!location) {
        helper.sendJsonResponse(res, 404, {
          "message": "no location with id " + req.params.locationid
        });
        return;
      } else if (err) {
        helper.sendJsonResponse(res, 404, err);
        return;
      }
      doc.theme = req.body.theme,
      doc.address = req.body.address,
      doc.datum = req.body.datum,
      doc.coords = [parseFloat(req.body.longitude),
        parseFloat(req.body.latitude)],
      doc.participants = req.body.participants,
      doc.required = req.body.required,
      doc.provided = req.body.provided

      doc.save(function(err, doc) {
        if (err) {
          helper.sendJsonResponse(res, 404, err);
          return;
        }
        helper.sendJsonResponse(res, 200, doc);
      });
    });
};

// DELETE location by ID
module.exports.delete = function(req, res) {
  LocationModel
    .findByIdAndRemove(req.params.locationid)
    .exec(function(err, location) {
      if (err) {
        helper.sendJsonResponse(res, 404, err);
        return;
      }
      helper.sendJsonResponse(res, 200, {
        "message": "successfully removed document with id " + req.params.locationid
      });
    });
}
